baseURL = "https://i.ppapi.cn"
languageCode = "zh-CN"
title = "网址导航"
theme = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
publishDir = "publish"


[params]
    author        = "qxsugar"
    description   = "网址导航 | qxsugar | Hugo"
    siteurl       = "./"
    about         = "/about"                                       # 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/qxsugar/so"
    enablePreLoad = true		    		                       # 网站完全打开前预加载动画
    textPreLoad   = "Hugo 网址导航主题" 		                       # 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false                                          # 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			               # 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.webp"             # logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    baiduhmid     = 'efccc04cb44fc49faddac5876180b369'             # 百度统计 hm.src 的 ID

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/favicon.png"
    searchImageL      = "assets/images/dna-bg.jpg"		#搜索部分浅色背景图
    searchImageD      = "assets/images/dna-bg.jpg"		#搜索部分深色背景图
    logoExpandLight   = "assets/images/bt8-expand-light.png"
    logoExpandDark    = "assets/images/bt8-expand-dark.png"
    logoCollapseLight = "assets/images/bt.png"
    logoCollapseDark  = "assets/images/bt.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '&copy; 2021 - {year} By [qxsugar](https://github.com/qxsugar)'
